# Generated by Django 4.0.6 on 2022-07-05 06:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='followers',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='authentication',
            name='star_image',
            field=models.ImageField(blank=True, null=True, upload_to=''),
        ),
    ]
