# Generated by Django 4.0.6 on 2022-07-10 05:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0007_sellerprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='sellerprofile',
            name='email',
            field=models.EmailField(blank=True, max_length=500, null=True),
        ),
        migrations.AddField(
            model_name='sellerprofile',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
