# Generated by Django 4.0 on 2022-07-10 17:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_categories'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='category',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='base.categories'),
        ),
        migrations.AlterField(
            model_name='categories',
            name='product',
            field=models.ManyToManyField(to='base.Authentication'),
        ),
    ]
