# Generated by Django 4.0 on 2022-07-10 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_authentication_category_alter_categories_product'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='authentication',
            name='category',
        ),
        migrations.AddField(
            model_name='authentication',
            name='category',
            field=models.ManyToManyField(to='base.Categories'),
        ),
    ]
