# Generated by Django 4.0.6 on 2022-07-12 06:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0011_remove_authentication_category_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='is_on_sale',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
