# Generated by Django 4.0.6 on 2022-07-13 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_authentication_sale_amount'),
    ]

    operations = [
        migrations.AlterField(
            model_name='authentication',
            name='category',
            field=models.ManyToManyField(blank=True, to='base.categories'),
        ),
    ]
