# Generated by Django 4.0.6 on 2022-07-14 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_alter_authentication_category'),
    ]

    operations = [
        migrations.AddField(
            model_name='authentication',
            name='offers',
            field=models.TextField(blank=True, null=True),
        ),
    ]
